version: '3'

services:
  apache-php:
    build: ./
    volumes:
      - ./:/var/www/html/
    ports:
      - "8080:80"
  mysql:
    image: mysql:8
    ports:
      - "3308:3308"
    volumes:
      - ./mysql:/var/lib/mysql
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: 0000
